### ISSUE TITLE
Better handling nil values

### ISSUE THREAD

**Issue by cblock** [spatchcock/quantify#18]
Currently nil values for quantities are automatically coerced into a 0.0 Float representation. My feeling is that this is not quite right. 

Consider a use case where a user enters quantities via html form and chooses _not_ to assign a quantity.  After saving the form the quantity would automagically be converted into a 0.0 value (unless some extra logic in controllers / models fixes that).

I'd like to propose `Quantity.new(nil,nil).to_s => "nil 1"` i.e. a valid  quantity with value `nil` and unit `unity`.

...and I'm happy to send in an appropriate pull request if you feel that this is a reasonable change to the behavior of the API.

**Comment by cblock** [comment]
Thanks again for the quick merge!

**Comment by spatchcock** [comment]
No problem mate. Thanks for the change.
