### ISSUE TITLE
Make unity have blank name and symbol

### ISSUE THREAD

**Issue by spatchcock** [spatchcock/quantify#23]

**Comment by spatchcock** [comment]
from cblock:

"...and one more thing: In this context it would be nice to switch the unity symbol from 1 to an empty String.
75.0 1 for a unitless quantity looks quite strange to me."

**Comment by cblock** [comment]
Great! I'd like to suggest the following:

``` ruby
quantity = Quantity.new(75)
quantity.unit.label     #=> :unity
quantity.unit.symbol    #=> ""
quantity.unit.name      #=> ""     #(even after i18n applied)
quantity.to_s           #=> "75"   #note: no whitespace after 75
```

**Comment by spatchcock** [comment]
This is now done:

https://github.com/spatchcock/quantify/blob/master/spec/quantity_spec.rb#L29
