### ISSUE TITLE
Gem::Exception: ruby_code case not handled: Syck::PrivateType

### ISSUE THREAD

**Issue by ghost** [spatchcock/quantify#37]
I get this error when I push to Heroku:

```
   Gem::Exception: ruby_code case not handled: Syck::PrivateType
   An error occurred while installing quantify (3.2.1), and Bundler cannot
   continue.
   Make sure that `gem install quantify -v '3.2.1'` succeeds before bundling.

   Failed to install gems via Bundler.

   Heroku push rejected, failed to compile Ruby/rails app
```

The gem works fine locally and I don't have problems with other gems, any ideas why I get this message using quantify?

**Comment by spatchcock** [comment]
Hey,

This is not something I have seen before, but a quick google returned this: http://help.rubygems.org/discussions/problems/483-gems-built-with-rubygems-150-ruby-192-do-not-install-properly-with-150-187

Do you know what versions of Ruby and Rubygems you are using? Are they different in your local environment and Heroku?

**Comment by ghost** [comment]
I solved the issue by specifying the same ruby version on Heroku as the one in my local environment (1.9.3). Thanks for the help and a great gem!

**Comment by spatchcock** [comment]
Hey. Thanks! Glad to hear you've managed to solve it.
