### ISSUE TITLE
Error parsing cubic feet

### ISSUE THREAD

**Issue by Floppy** [spatchcock/quantify#8]
[1] pry(main)> Quantity.parse('1 cubic foot')
=> [1.0 ]
[2] pry(main)> Quantity.parse('1 cubic foot')
NoMethodError: undefined method `label' for nil:NilClass
from /Users/james/.rvm/gems/ruby-1.8.7-p352@askamee/gems/activesupport-3.1.1/lib/active_support/whiny_nil.rb:48:in`method_missing'

Apparently it's the same for metres.

**Comment by Floppy** [comment]
Strange (or not) that it works unit-free the first time, but fails the second time.

**Comment by spatchcock** [comment]
Hey mate,

I have released 3.1.0. This issue should work with this new version.

Cheers
